annotations:
  category: Analytics
apiVersion: v2
appVersion: 7.14.2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Kibana is an open source, browser based analytics and search dashboard for Elasticsearch.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kibana
icon: https://bitnami.com/assets/stacks/kibana/img/kibana-stack-220x234.png
keywords:
  - kibana
  - analytics
  - monitoring
  - metrics
  - logs
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: kibana
sources:
  - https://github.com/bitnami/bitnami-docker-kibana
  - https://www.elastic.co/products/kibana
version: 9.0.4
