annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.18.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Contour Ingress controller for Kubernetes
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/contour
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
keywords:
  - ingress
  - envoy
  - contour
maintainers:
  - name: cellebyte
    url: https://github.com/Cellebyte
  - email: containers@bitnami.com
    name: Bitnami
name: contour
sources:
  - https://github.com/projectcontour/contour
  - https://github.com/envoyproxy/envoy
  - https://github.com/bitnami/bitnami-docker-contour
  - https://projectcontour.io
version: 5.5.3
