mediawikiHost: mediawiki.local
service:
  type: ClusterIP
ingress:
  enabled: true
  tls: true
  hostname: mediawiki.local
livenessProbe:
  httpGet:
    httpHeaders: []
readinessProbe:
  httpGet:
    httpHeaders: []
