annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.0.3
dependencies:
  - condition: wavefront.enabled
    name: wavefront
    repository: https://charts.bitnami.com/bitnami
    version: 3.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Wavefront Storage Adapter is a Prometheus integration to transfer metrics from Prometheus to Wavefront. It lets you save Prometheus data in Wavefront without changing your existing Prometheus setup.
engine: gotpl
home: https://github.com/wavefrontHQ/prometheus-storage-adapter
icon: https://bitnami.com/assets/stacks/wavefront-prometheus-storage-adapter/img/wavefront-prometheus-storage-adapter-stack-220x234.png
keywords:
  - alerting
  - adapter
  - metrics
  - monitoring
  - observability
  - wavefront
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wavefront-prometheus-storage-adapter
sources:
  - https://github.com/bitnami/bitnami-docker-wavefront-prometheus-storage-adapter
version: 1.0.8
