chart-dirs:
  - riftbit
chart-repos:
  - riftbit=https://charts.riftbit.com/riftbit
debug: true
excluded-charts:
  - common
  - kubeapps
  - kibana
  - kong
  - mariadb-galera
  - discourse
  - ejbca
  - wavefront
  - harbor
  - dataplatform-bp1
  - dataplatform-bp2
remote: origin
