chart-dirs:
  - riftbit
chart-repos:
  - riftbit=https://charts.riftbit.com/riftbit
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
