debug: true
remote: upstream
# remote: origin
chart-dirs:
  - riftbit
# chart-repos:
#   - riftbit=https://charts.riftbit.com/riftbit
check-version-increment: true
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
