# See https://github.com/helm/chart-testing#configuration
debug: true
# remote: upstream
remote: origin
target-branch: main
chart-dirs:
  - riftbit
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami/
helm-extra-args: --timeout 600s

check-version-increment: true
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true