annotations:
  category: HumanResourceManagement
apiVersion: v2
appVersion: 4.8.0-0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: OrangeHRM is a free HR management system that offers a wealth of modules to suit the needs of your business.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/orangehrm
icon: https://bitnami.com/assets/stacks/orangehrm/img/orangehrm-stack-220x234.png
keywords:
  - orangehrm
  - http
  - https
  - web
  - application
  - php
  - human resources
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: orangehrm
sources:
  - https://github.com/bitnami/bitnami-docker-orangehrm
  - https://www.orangehrm.com
version: 10.1.20
