# Test values file for generating all of the yaml and check that
# the rendering is correct

postgresql:
  pdb:
    create: true

pgpool:
  pdb:
    create: true

networkPolicy:
  enabled: true
  allowExternal: false

metrics:
  enabled: true
  ## Kubeval doesn't recognise ServiceMonitor as a valid K8s object
  # serviceMonitor:
  #   enabled: true
