{{- if .Values.bucketweb.ingress.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-bucketweb
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.bucketweb.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := .Values.bucketweb.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if and .Values.bucketweb.ingress.ingressClassName (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.bucketweb.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    {{- if .Values.bucketweb.ingress.hostname }}
    - host: {{ .Values.bucketweb.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.bucketweb.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ .Values.bucketweb.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s"  (include "common.names.fullname" .) "bucketweb") "servicePort" "http" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range .Values.bucketweb.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s"  (include "common.names.fullname" $) "bucketweb") "servicePort" "http" "context" $) | nindent 14 }}
    {{- end }}
  {{- if or .Values.bucketweb.ingress.tls .Values.bucketweb.ingress.extraTls .Values.bucketweb.ingress.hosts }}
  tls:
    {{- if or .Values.bucketweb.ingress.secrets .Values.bucketweb.ingress.tls }}
    - hosts:
        - {{ .Values.bucketweb.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.bucketweb.ingress.hostname }}
    {{- end }}
    {{- if .Values.bucketweb.ingress.extraTls }}
    {{- toYaml .Values.bucketweb.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
