{{- if and .Values.bucketweb.enabled .Values.bucketweb.pdb.create }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.names.fullname" . }}-bucketweb
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.bucketweb.pdb.minAvailable }}
  minAvailable: {{ .Values.bucketweb.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.bucketweb.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.bucketweb.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: bucketweb
{{- end }}
