annotations:
  category: Database
apiVersion: v2
appVersion: 4.0.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Apache Cassandra is a free and open-source distributed database management system designed to handle large amounts of data across many commodity servers, providing high availability with no single point of failure. Cassandra offers robust support for clusters spanning multiple datacenters, with asynchronous masterless replication allowing low latency operations for all clients.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/cassandra
icon: https://bitnami.com/assets/stacks/cassandra/img/cassandra-stack-220x234.png
keywords:
  - cassandra
  - database
  - nosql
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: cassandra
sources:
  - https://github.com/bitnami/bitnami-docker-cassandra
  - http://cassandra.apache.org
version: 8.0.4
