annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 7.8.0
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: The JasperReports server can be used as a stand-alone or embedded reporting and BI server that offers web-based reporting, analytic tools and visualization, and a dashboard feature for compiling multiple custom views
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/jasperreports
icon: https://bitnami.com/assets/stacks/jasperserver/img/jasperserver-stack-220x234.png
keywords:
  - business intelligence
  - java
  - jasper
  - reporting
  - analytic
  - visualization
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: jasperreports
sources:
  - https://github.com/bitnami/bitnami-docker-jasperreports
  - http://community.jaspersoft.com/project/jasperreports-server
version: 11.0.5
