{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if $query.enabled }}

{{- $shards := int 0 }}

{{- if .Values.storegateway.sharded.hashPartitioning.shards }}
  {{- $shards = int .Values.storegateway.sharded.hashPartitioning.shards }}
{{- else }}
  {{- $shards = len .Values.storegateway.sharded.timePartitioning }}
{{- end }}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-query
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: query
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $query.replicaCount }}
  strategy:
    type: {{ $query.strategyType }}
    {{- if (eq "Recreate" $query.strategyType) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: query
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: query
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if $query.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" $query.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap $query.podAnnotations }}
      annotations:
        {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
        checksum/ruler-configuration: {{ include (print $.Template.BasePath "/query/sd-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if $query.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" $query.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "thanos.imagePullSecrets" . | nindent 6 }}
      serviceAccount: {{ include "thanos.serviceaccount.name" (dict "component" "query" "context" $) }}
      {{- if $query.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" $query.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if $query.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" $query.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" $query.podAffinityPreset "component" "query" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" $query.podAntiAffinityPreset "component" "query" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" $query.nodeAffinityPreset.type "key" $query.nodeAffinityPreset.key "values" $query.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if $query.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" $query.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if $query.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" $query.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if $query.priorityClassName }}
      priorityClassName: {{ $query.priorityClassName | quote }}
      {{- end }}
      {{- if $query.podSecurityContext.enabled }}
      securityContext: {{- omit $query.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        {{- if $query.extraContainers }}
        {{- include "common.tplvalues.render" (dict "value" $query.extraContainers "context" $) | nindent 8 }}
        {{- end }}
        - name: query
          image: {{ include "thanos.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if $query.containerSecurityContext.enabled }}
          securityContext: {{- omit $query.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          args:
            - query
            - --log.level={{ $query.logLevel }}
            - --log.format={{ $query.logFormat }}
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            {{- if kindIs "string" $query.replicaLabel }}
            - --query.replica-label={{ $query.replicaLabel }}
            {{- else }}
            {{- range $query.replicaLabel }}
            - --query.replica-label={{ . }}
            {{- end }}
            {{- end }}
            {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
            - --store.sd-files=/conf/servicediscovery.yml
            {{- end }}
            {{- if and $query.dnsDiscovery.enabled $query.dnsDiscovery.sidecarsService $query.dnsDiscovery.sidecarsNamespace }}
            - --store=dnssrv+_grpc._tcp.{{- include "common.tplvalues.render" ( dict "value" $query.dnsDiscovery.sidecarsService "context" $) -}}.{{- include "common.tplvalues.render"  ( dict "value" $query.dnsDiscovery.sidecarsNamespace "context" $) -}}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- if and .Values.storegateway.enabled .Values.storegateway.sharded.enabled }}
            {{- range $index, $_ := until $shards }}
            - --store=dnssrv+_grpc._tcp.{{ include "common.names.fullname" $ }}-storegateway-{{ toString $index }}.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }}
            {{- end }}
            {{- end }}
            {{- if and .Values.storegateway.enabled $query.dnsDiscovery.enabled (not .Values.storegateway.sharded.enabled )}}
            - --store=dnssrv+_grpc._tcp.{{ include "common.names.fullname" . }}-storegateway{{ if .Values.storegateway.service.additionalHeadless }}-headless{{ end }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- if and .Values.ruler.enabled $query.dnsDiscovery.enabled }}
            - --store=dnssrv+_grpc._tcp.{{ include "common.names.fullname" . }}-ruler{{ if .Values.ruler.service.additionalHeadless }}-headless{{ end }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- if and .Values.receive.enabled $query.dnsDiscovery.enabled }}
            - --store=dnssrv+_grpc._tcp.{{ include "common.names.fullname" . }}-receive{{ if .Values.receive.service.additionalHeadless }}-headless{{ end }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
            {{- end }}
            {{- range $query.stores }}
            - --store={{ . }}
            {{- end }}
            {{- if $query.grpcTLS.server.autoGenerated }}
            - --grpc-server-tls-cert=/tls/server/tls.crt
            - --grpc-server-tls-key=/tls/server/tls.key
            - --grpc-server-tls-client-ca=/tls/server/ca.crt
            {{- else }}
            {{- if or $query.grpcTLS.server.secure $query.grpcTLS.server.existingSecret}}
            - --grpc-server-tls-cert=/tls/server/{{ include "common.secrets.key" (dict "existingSecret" .Values.query.grpcTLS.server.existingSecret "key" "tls-cert") }}
            - --grpc-server-tls-key=/tls/server/{{ include "common.secrets.key" (dict "existingSecret" .Values.query.grpcTLS.server.existingSecret "key" "tls-key") }}
            {{- if or $query.grpcTLS.server.ca $query.grpcTLS.server.existingSecret }}
            - --grpc-server-tls-client-ca=/tls/server/{{ include "common.secrets.key" (dict "existingSecret" .Values.query.grpcTLS.server.existingSecret "key" "ca-cert") }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if $query.grpcTLS.client.autoGenerated }}
            - --grpc-client-tls-secure
            - --grpc-client-tls-cert=/tls/client/tls.crt
            - --grpc-client-tls-key=/tls/client/tls.key
            - --grpc-client-tls-ca=/tls/client/ca.crt
            {{- else }}
            {{- if or $query.grpcTLS.client.secure $query.grpcTLS.client.existingSecret }}
            - --grpc-client-tls-secure
            {{- if or $query.grpcTLS.client.cert $query.grpcTLS.client.existingSecret }}
            - --grpc-client-tls-cert=/tls/client/{{ include "common.secrets.key" (dict "existingSecret" .Values.query.grpcTLS.client.existingSecret "key" "tls-cert") }}
            {{- end }}
            {{- if or $query.grpcTLS.client.key $query.grpcTLS.client.existingSecret }}
            - --grpc-client-tls-key=/tls/client/{{ include "common.secrets.key" (dict "existingSecret" .Values.query.grpcTLS.client.existingSecret "key" "tls-key") }}
            {{- end }}
            {{- if or $query.grpcTLS.client.ca $query.grpcTLS.client.existingSecret }}
            - --grpc-client-tls-ca=/tls/client/{{ include "common.secrets.key" (dict "existingSecret" .Values.query.grpcTLS.client.existingSecret "key" "ca-cert") }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if $query.grpcTLS.client.servername }}
            - --grpc-client-server-name={{$query.grpcTLS.client.servername}}
            {{- end }}
            {{- if $query.extraFlags }}
            {{- $query.extraFlags | toYaml | nindent 12 }}
            {{- end }}
          {{- if .Values.query.extraEnv }}
          env:
            {{- toYaml .Values.query.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
          {{- if $query.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: {{ $query.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ $query.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ $query.livenessProbe.periodSeconds }}
            successThreshold: {{ $query.livenessProbe.successThreshold }}
            failureThreshold: {{ $query.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if $query.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: {{ $query.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ $query.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ $query.readinessProbe.periodSeconds }}
            successThreshold: {{ $query.readinessProbe.successThreshold }}
            failureThreshold: {{ $query.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if $query.resources }}
          resources: {{- toYaml $query.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
      {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
            - name: sd-config
              mountPath: /conf/servicediscovery.yml
              subPath: servicediscovery.yml
      {{- end }}
      {{- if $query.grpcTLS.server.secure }}
            - name: tls-server
              mountPath: /tls/server
      {{- end }}
      {{- if $query.grpcTLS.client.secure }}
            - name: tls-client
              mountPath: /tls/client
      {{- end }}
            {{- if .Values.query.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.query.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      volumes:
      {{- if or (include "thanos.query.createSDConfigmap" .) $query.existingSDConfigmap }}
        - name: sd-config
          configMap:
            name: {{ include "thanos.query.SDConfigmapName" . }}
      {{- end }}
      {{- if or $query.grpcTLS.server.secure $query.grpcTLS.server.existingSecret $query.grpcTLS.server.autoGenerated }}
        - name: tls-server
          secret:
            {{- if $query.grpcTLS.server.autoGenerated }}
            secretName: {{ printf "%s-crt" (include "common.names.fullname" .) }}
            {{- else }}
            secretName: {{ include "common.secrets.name" (dict "existingSecret" .Values.query.grpcTLS.server.existingSecret "defaultNameSuffix" "query-tls-server" "context" $) }}
            {{- end }}
      {{- end }}
      {{- if or $query.grpcTLS.client.secure $query.grpcTLS.client.existingSecret $query.grpcTLS.client.autoGenerated }}
        - name: tls-client
          secret:
            {{- if $query.grpcTLS.client.autoGenerated }}
            secretName: {{ printf "%s-crt" (include "common.names.fullname" .) }}
            {{- else }}
            secretName: {{ include "common.secrets.name" (dict "existingSecret" .Values.query.grpcTLS.client.existingSecret "defaultNameSuffix" "query-tls-client" "context" $) }}
            {{- end }}
      {{- end }}
        {{- if .Values.query.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.query.extraVolumes "context" $) | nindent 8 }}
        {{- end }}

{{- end }}
