{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if $query.ingress.grpc.enabled -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-grpc
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: query
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $query.ingress.grpc.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- range $key, $value := $query.ingress.grpc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if $query.ingress.grpc.hostname }}
    - host: {{ $query.ingress.grpc.hostname }}
      http:
        paths:
          - path: {{ $query.ingress.path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" .) }}
            pathType: {{ $query.ingress.pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s" (include "common.names.fullname" .) "query") "servicePort" "grpc" "context" $)  | nindent 14 }}
    {{- end }}
    {{- range $query.ingress.grpc.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (printf "%s-%s" (include "common.names.fullname" $) "query") "servicePort" "grpc" "context" $) | nindent 14 }}
    {{- end }}
  {{- if or $query.ingress.grpc.tls $query.ingress.grpc.extraTls $query.ingress.grpc.hosts }}
  tls:
    {{- if $query.ingress.grpc.tls }}
    - hosts:
        - {{ $query.ingress.grpc.hostname }}
      secretName: {{ printf "%s-tls" $query.ingress.grpc.hostname }}
    {{- end }}
    {{- if $query.ingress.grpc.extraTls }}
    {{- toYaml $query.ingress.grpc.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
