{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if and $query.enabled $query.pspEnabled $query.rbac.create -}}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}-query
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: query
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "common.names.fullname" . }}-query
{{- end -}}
