{{- $query := (include "thanos.query.values" . | fromYaml) -}}
{{- if $query.ingress.enabled }}
{{- range $query.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-query
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: query
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
