{{- if (include "discourse.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-discourse
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and (.Values.discourse.password) (not .Values.discourse.existingSecret) }}
  discourse-password: {{ .Values.discourse.password | b64enc | quote }}
  {{- else if not .Values.discourse.existingSecret }}
  discourse-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.discourse.smtp.password) (.Values.discourse.smtp.enabled) (not .Values.discourse.smtp.existingSecret) }}
  smtp-password: {{ .Values.discourse.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
