{{- if and (.Values.server.enabled) (not .Values.server.tlsSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "common.names.fullname" . }}-server
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- if .Values.server.tlsFiles.ca }}
  {{- toYaml .Values.server.tlsFiles | nindent 2 }}
{{- else }}
  {{- include "kiam.server.gen-certs" . | nindent 2 }}
{{- end -}}
{{- end }}
