{{- if and .Values.forwarder.enabled .Values.forwarder.rbac.create }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
  {{- if .Values.forwarder.rbac.pspEnabled }}
  - apiGroups:
      - "policy"
    resources:
      - "podsecuritypolicies"
    resourceNames:
      - {{ include "common.names.fullname" . }}-forwarder
    verbs:
      - "use"
  {{- end }}
{{- end }}
