{{- if and (or .Values.skipper.enabled .Values.server.configuration.streamingEnabled) .Values.skipper.pdb.create }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scdf.fullname" . }}-skipper
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: skipper
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.skipper.pdb.minAvailable }}
  minAvailable: {{ .Values.skipper.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.skipper.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.skipper.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: skipper
{{- end }}
