annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.9.8
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Wavefront HPA Adapter for Kubernetes is a Kubernetes Horizontal Pod Autoscaler adapter. It enables Kubernetes workloads to be scaled based on Wavefront metrics.
engine: gotpl
home: https://github.com/wavefrontHQ/wavefront-kubernetes-adapter
icon: https://bitnami.com/assets/stacks/wavefront-hpa-adapter/img/wavefront-hpa-adapter-stack-220x234.png
keywords:
  - alerting
  - adapter
  - metrics
  - monitoring
  - observability
  - wavefront
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wavefront-hpa-adapter
sources:
  - https://github.com/bitnami/bitnami-docker-wavefront-hpa-adapter
version: 0.1.5
