{{- if .Values.mongos.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-mongos
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mongos
data:
  mongodb.conf: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.mongos.config "context" $) | nindent 4 }}
{{- end }}
