{{- if .Values.dataplatform.exporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dataplatform-exporter
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.dataplatform.exporter.service.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.dataplatform.exporter.service.labels "context" $ ) | nindent 4 }}
    {{- end }}
  name: "{{ include "dataplatform.exporter-name" . }}"
  {{- if or .Values.dataplatform.exporter.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.dataplatform.exporter.service.annotations }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.dataplatform.exporter.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.dataplatform.exporter.service.type }}
  {{ if eq .Values.dataplatform.exporter.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.dataplatform.exporter.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.dataplatform.exporter.service.type "LoadBalancer") (not (empty .Values.dataplatform.exporter.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.dataplatform.exporter.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: tcp-client
      port: {{ .Values.dataplatform.exporter.service.ports.http }}
      protocol: TCP
      targetPort: exporter-port
      {{- if and (or (eq .Values.dataplatform.exporter.service.type "NodePort") (eq .Values.dataplatform.exporter.service.type "LoadBalancer")) (not (empty .Values.dataplatform.exporter.service.nodePorts.http)) }}
      nodePort: {{ .Values.dataplatform.exporter.service.nodePorts.http }}
      {{- else if eq .Values.dataplatform.exporter.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dataplatform-exporter
{{ end }}
