annotations:
  category: MachineLearning
apiVersion: v2
appVersion: 1.4.2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    version: 10.x.x
description: JupyterHub brings the power of notebooks to groups of users. It gives users access to computational environments and resources without burdening the users with installation and maintenance tasks
engine: gotpl
home: https://jupyter.org/hub
icon: https://bitnami.com/assets/stacks/jupyterhub/img/jupyterhub-stack-220x234.png
keywords:
  - python
  - scientific
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: jupyterhub
sources:
  - https://github.com/bitnami/bitnami-docker-jupyterhub
  - https://github.com/jupyterhub/jupyterhub
version: 0.1.19
