{{- if and .Values.metrics.enabled .Values.metrics.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- toYaml .Values.metrics.prometheusRules.selector | nindent 4 }}
spec:
  groups:
  - name: {{ include "common.names.fullname" . }}
    rules:
      {{- toYaml .Values.metrics.prometheusRules.rules | nindent 6 }}
{{- end }}

