annotations:
  category: MachineLearning
apiVersion: v2
appVersion: 1.9.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Deep learning platform that accelerates the transition from research prototyping to production deployment
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/pytorch
icon: https://bitnami.com/assets/stacks/pytorch/img/pytorch-stack-220x234.png
keywords:
  - pytorch
  - python
  - machine
  - learning
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: pytorch
sources:
  - https://github.com/bitnami/bitnami-docker-pytorch
  - http://pytorch.org/
version: 2.3.14
