{{- if and (not .Values.configsvr.external.host) .Values.configsvr.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-configsvr
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: configsvr
data:
  mongodb.conf: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.configsvr.config "context" $) | nindent 4 }}
{{- end }}
