apiVersion: v2
appVersion: 1.0.0
version: 0.1.0
description: RedisInsight - The GUI for Redis
home: https://redis.com/redis-enterprise/redis-insight/
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
# maintainers:
#   - name: sebastien-prudhomme
#     email: sebastien.prudhomme@gmail.com
name: redisinsight
type: application
keywords:
  - redis
  - gui
