annotations:
  category: CRM
apiVersion: v2
appVersion: 14.0.20210910
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: A suite of web based open source business apps.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/odoo
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
keywords:
  - odoo
  - crm
  - www
  - http
  - web
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: odoo
sources:
  - https://github.com/bitnami/bitnami-docker-odoo
  - https://www.odoo.com/
version: 19.0.8
