annotations:
  category: Forum
apiVersion: v2
appVersion: 3.3.4
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: Community forum that supports the notion of users and groups, file attachments, full-text search, notifications and more.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phpbb
icon: https://bitnami.com/assets/stacks/phpbb/img/phpbb-stack-220x234.png
keywords:
  - phpbb
  - forum
  - http
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: phpbb
sources:
  - https://github.com/bitnami/bitnami-docker-phpbb
  - https://www.phpbb.com/
version: 10.1.20
