# Test values file for generating all of the yaml and check that
# the rendering is correct
service:
  type: ClusterIP
ingress:
  enabled: true
  tls: true
  hostname: tomcat.local
volumePermissions:
  enabled: true
