magentoHost: magento.local
mariadb:
  enabled: false
externalDatabase:
  host: database.local
ingress:
  enabled: true
metrics:
  enabled: true
# Avoids issues with yamllint
livenessProbe:
  httpGet:
    httpHeaders: []
readinessProbe:
  httpGet:
    httpHeaders: []
