{{- if and .Values.shards .Values.shardsvr.arbiter.replicas .Values.shardsvr.arbiter.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-shardsvr-arbiter
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: shardsvr-arbiter
data:
  mongodb.conf: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.shardsvr.arbiter.config "context" $) | nindent 4 }}
{{- end }}
