annotations:
  category: E-Commerce
apiVersion: v2
appVersion: 2.4.3
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - magento-database
    version: 9.x.x
  - condition: elasticsearch.enabled
    name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 17.x.x
description: A feature-rich flexible e-commerce solution. It includes transaction options, multi-store functionality, loyalty programs, product categorization and shopper filtering, promotion rules, and more.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/magento
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-220x234.png
keywords:
  - magento
  - e-commerce
  - http
  - web
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: magento
sources:
  - https://github.com/bitnami/bitnami-docker-magento
  - https://magento.com/
version: 19.0.1
