apiVersion: v2
appVersion: 0.1.11
description: Kubernetes cluster visualiser and graphical explorer
home: https://github.com/benc-uk/kubeview
icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kubeview
version: 2.6.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
