{{ if and (or .Values.input .Values.filter .Values.output) (not .Values.existingConfiguration) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- if (or .Values.input .Values.filter .Values.output) }}
  logstash.conf: |-
{{- if .Values.input }}
    input {
    {{- include "common.tplvalues.render" (dict "value" .Values.input "context" $) | nindent 6 }}
    }
{{- end }}
{{- if .Values.filter }}
    filter {
    {{- include "common.tplvalues.render" (dict "value" .Values.filter "context" $) | nindent 6 }}
    }
{{- end }}
{{- if .Values.output }}
    output {
    {{- include "common.tplvalues.render" (dict "value" .Values.output "context" $) | nindent 6 }}
    }
{{- end }}
{{ end }}
{{ end }}
