apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ if .Values.server.masterKey }}
  master-key: {{ .Values.server.masterKey | b64enc | quote }}
  {{ else }}
  master-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.dashboard.enabled }}
  {{ if .Values.dashboard.password }}
  parse-dashboard-password: {{ .Values.dashboard.password | b64enc | quote }}
  {{ else }}
  parse-dashboard-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ end }}
