annotations:
  category: Analytics
apiVersion: v2
appVersion: 1.7.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: kube-state-metrics.enabled
    name: kube-state-metrics
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
description: Chart for Wavefront Collector for Kubernetes
engine: gotpl
home: https://www.wavefront.com
icon: https://bitnami.com/assets/stacks/wavefront-collector/img/wavefront-collector-stack-220x234.png
keywords:
  - metric
  - monitoring
  - observability
  - alerting
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: wavefront
sources:
  - https://github.com/bitnami/bitnami-docker-wavefront-kubernetes-collector
  - https://github.com/bitnami/bitnami-docker-wavefront-proxy
  - https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
  - https://github.com/wavefrontHQ/wavefront-proxy
version: 3.1.12
