annotations:
  category: CMS
apiVersion: v2
appVersion: 3.10.2
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    version: 9.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: PHP content management system (CMS) for publishing web content
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/joomla
icon: https://bitnami.com/assets/stacks/joomla/img/joomla-stack-220x234.png
keywords:
  - joomla
  - cms
  - blog
  - http
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: joomla
sources:
  - https://github.com/bitnami/bitnami-docker-joomla
  - http://www.joomla.org/
version: 10.1.21
