annotations:
  category: Database
apiVersion: v2
appVersion: 11.13.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: Chart for PostgreSQL with HA architecture (using Replication Manager (repmgr) and Pgpool).
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
  - postgresql
  - repmgr
  - pgpool
  - postgres
  - database
  - sql
  - replication
  - cluster
  - high availability
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: postgresql-ha
sources:
  - https://github.com/bitnami/bitnami-docker-postgresql
  - https://www.postgresql.org/
version: 7.9.6
