annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 5.1.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: db.bundleTestDB
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - phpmyadmin-database
    version: 9.x.x
description: phpMyAdmin is an mysql administration frontend
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/phpmyadmin
icon: https://bitnami.com/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
  - mariadb
  - mysql
  - phpmyadmin
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: phpmyadmin
sources:
  - https://github.com/bitnami/bitnami-docker-phpmyadmin
  - https://www.phpmyadmin.net/
version: 8.2.13
