{{- if and .Values.receive.enabled .Values.receive.grpc.server.secure -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-receive-tls-server
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: receive
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  cert.pem: {{ .Values.receive.grpc.server.cert | b64enc | quote }}
  key.pem: {{ .Values.receive.grpc.server.key | b64enc | quote }}
  ca.pem : {{ .Values.receive.grpc.server.ca | b64enc | quote }}
{{ end }}
