{{- if and .Values.agent.enabled (not .Values.agent.tlsSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: agent
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ template "common.names.fullname" . }}-agent
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- if .Values.agent.tlsFiles.ca }}
  {{- toYaml .Values.agent.tlsFiles | nindent 2 }}
{{- else }}
  {{- include "kiam.agent.gen-certs" . | nindent 2 }}
{{- end -}}
{{- end }}
