annotations:
  category: CMS
apiVersion: v2
appVersion: 4.4.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: mariadb.enabled
    name: mariadb
    repository: https://charts.bitnami.com/bitnami
    tags:
      - osclass-database
    version: 9.x.x
description: Osclass is a php script that allows you to quickly create and manage your own free classifieds site.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/osclass
icon: https://bitnami.com/assets/stacks/osclass/img/osclass-stack-220x234.png
keywords:
  - osclass
  - classifieds
  - http
  - web
  - php
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: osclass
sources:
  - https://github.com/bitnami/bitnami-docker-osclass
  - https://osclass.org/
version: 11.0.13
