apiVersion: v2
appVersion: 0.9.2
description: Set of components that automatically adjust the amount of CPU and memory requested by pods running in the Kubernetes Cluster
home: https://github.com/kubernetes/autoscaler
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: vertical-pod-autoscaler
version: 3.6.0
dependencies:
  - name: common
    repository: https://charts.riftbit.com/
    # tags:
    #   - riftbit-common
    version: 1.x.x
