annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 2.4.49
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Chart for Apache HTTP Server
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/apache
icon: https://bitnami.com/assets/stacks/apache/img/apache-stack-220x234.png
keywords:
  - apache
  - http
  - https
  - www
  - web
  - reverse proxy
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: apache
sources:
  - https://github.com/bitnami/bitnami-docker-apache
  - https://httpd.apache.org
version: 8.7.0
